# Generated by Django 5.2.6 on 2025-09-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitapp', '0003_remove_servicerequest_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitapp.customuser'),
        ),
    ]
